### PR TITLE
 JENKINS-50364: Encode file names with space correctly 

### PR DESCRIPTION
**Pull request by TobiX**
This probably achieves the same as #21, but I restricted myself to only fix the encoding problem (which is already reported in  JENKINS-50364 and was a regression of JENKINS-37026). The change is covered by a simple HtmlUnit test case, which tries to click the links for three unusual file names.

PS: Currently test workspaces are shipped as ZIP files, but they are probably small enough to just put them into the project directly. WDYT?

### CODE REVIEW

**Comment by TobiX** [comment]
@pjhampton *ping* - Rebased to remove conflict

**Comment by pjhampton** [comment]
Thanks @TobiX! 👍 I will try to do a release soon

**Comment by phytoporg** [comment]
> Thanks @TobiX! 👍 I will try to do a release soon

Hi @pjhampton , is there a chance we'll see a release with this fix in the near future?

**Comment by pjhampton** [comment]
Hey everyone

Sorry - life has gotten in the way recently. Last time I attempted the release it failed. I will try again this weekend!

**Pull request merged**
