### PR TITLE
[JENKINS-36305] Fix HTTP404 when browsing test actions from test result

### PR DESCRIPTION
**Pull request by Vlatombe**
Downstream of https://github.com/jenkinsci/junit-plugin/pull/50

### CODE REVIEW

**Comment by pjhampton** [comment]
Hey @Vlatombe 

It looks like this could now be updated to v1.24. I'm sure you're super busy - but it would be great to update this, rerun the build and get it merged.

**Comment by jglick** [comment]
I had concerns about mergeability of the upstream PR.

**Comment by pjhampton** [comment]
ahh fair enough

**Comment by pjhampton** [comment]
Going to time this out.

**Pull request closed without merging**
