### PR TITLE
[INFRA-1310] Avoid bogus Stapler transitive dep

### PR DESCRIPTION
**Pull request by jglick**
Workaround until https://github.com/jenkinsci/jquery-plugin/pull/3 is released.

@reviewbybees

### CODE REVIEW

**Comment by jglick** [comment]
@reviewbybees done

**Comment by oleg-nenashev** [comment]
Would be better to just release a new version of the Stapler component and then the JQuery Plugin

**Comment by jglick** [comment]
Well, that could take a while; this is mergeable in the short term.

**Comment by jglick** [comment]
CC @abayer as apparent maintainer.

**Comment by abayer** [comment]
...how'd I end up the maintainer here? =)

**Comment by jglick** [comment]
> how'd I end up the maintainer here?

By cutting the last release? Is there someone else?

**Pull request merged**
