### PR TITLE
[JENKINS-26274] Fixed.

### PR DESCRIPTION
**Pull request by intelradoux**
Add JUnit plugin dependencies so that extension is registered

### CODE REVIEW

**Comment by jglick** [comment]
[JENKINS-26274](https://issues.jenkins-ci.org/browse/JENKINS-26274)

**Comment by intelradoux** [comment]
Hello,

More than 3 years later, I'm not using this plugin anymore, It will take me
too much time to understand/rebuilt/test those stuff.

just cancel this pr.

2018-02-16 15:16 GMT+01:00 Jesse Glick <notifications@github.com>:

**Comment by jglick** [comment]
Whatever this was fixing, I suspect it is obsolete and could be closed.

**Comment by pjhampton** [comment]
Look like it. Please close.

**Pull request closed without merging**
